# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fankux/app/fankux/webc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fankux/app/fankux/webc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fankux/app/fankux/webc/CMakeFiles /home/fankux/app/fankux/webc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fankux/app/fankux/webc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named consumer

# Build rule for target.
consumer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 consumer
.PHONY : consumer

# fast build rule for target.
consumer/fast:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/build
.PHONY : consumer/fast

#=============================================================================
# Target rules for targets named provider

# Build rule for target.
provider: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 provider
.PHONY : provider

# fast build rule for target.
provider/fast:
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/build
.PHONY : provider/fast

#=============================================================================
# Target rules for targets named threadpool

# Build rule for target.
threadpool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threadpool
.PHONY : threadpool

# fast build rule for target.
threadpool/fast:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/build
.PHONY : threadpool/fast

#=============================================================================
# Target rules for targets named webc

# Build rule for target.
webc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 webc
.PHONY : webc

# fast build rule for target.
webc/fast:
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/build
.PHONY : webc/fast

#=============================================================================
# Target rules for targets named worker

# Build rule for target.
worker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 worker
.PHONY : worker

# fast build rule for target.
worker/fast:
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/build
.PHONY : worker/fast

RpcConsumer.o: RpcConsumer.cpp.o
.PHONY : RpcConsumer.o

# target to build an object file
RpcConsumer.cpp.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/RpcConsumer.cpp.o
.PHONY : RpcConsumer.cpp.o

RpcConsumer.i: RpcConsumer.cpp.i
.PHONY : RpcConsumer.i

# target to preprocess a source file
RpcConsumer.cpp.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/RpcConsumer.cpp.i
.PHONY : RpcConsumer.cpp.i

RpcConsumer.s: RpcConsumer.cpp.s
.PHONY : RpcConsumer.s

# target to generate assembly for a file
RpcConsumer.cpp.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/RpcConsumer.cpp.s
.PHONY : RpcConsumer.cpp.s

RpcServer.o: RpcServer.cpp.o
.PHONY : RpcServer.o

# target to build an object file
RpcServer.cpp.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/RpcServer.cpp.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/RpcServer.cpp.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/RpcServer.cpp.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/RpcServer.cpp.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/RpcServer.cpp.o
.PHONY : RpcServer.cpp.o

RpcServer.i: RpcServer.cpp.i
.PHONY : RpcServer.i

# target to preprocess a source file
RpcServer.cpp.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/RpcServer.cpp.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/RpcServer.cpp.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/RpcServer.cpp.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/RpcServer.cpp.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/RpcServer.cpp.i
.PHONY : RpcServer.cpp.i

RpcServer.s: RpcServer.cpp.s
.PHONY : RpcServer.s

# target to generate assembly for a file
RpcServer.cpp.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/RpcServer.cpp.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/RpcServer.cpp.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/RpcServer.cpp.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/RpcServer.cpp.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/RpcServer.cpp.s
.PHONY : RpcServer.cpp.s

Woker.o: Woker.cpp.o
.PHONY : Woker.o

# target to build an object file
Woker.cpp.o:
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/Woker.cpp.o
.PHONY : Woker.cpp.o

Woker.i: Woker.cpp.i
.PHONY : Woker.i

# target to preprocess a source file
Woker.cpp.i:
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/Woker.cpp.i
.PHONY : Woker.cpp.i

Woker.s: Woker.cpp.s
.PHONY : Woker.s

# target to generate assembly for a file
Woker.cpp.s:
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/Woker.cpp.s
.PHONY : Woker.cpp.s

arranger.o: arranger.c.o
.PHONY : arranger.o

# target to build an object file
arranger.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/arranger.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/arranger.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/arranger.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/arranger.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/arranger.c.o
.PHONY : arranger.c.o

arranger.i: arranger.c.i
.PHONY : arranger.i

# target to preprocess a source file
arranger.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/arranger.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/arranger.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/arranger.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/arranger.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/arranger.c.i
.PHONY : arranger.c.i

arranger.s: arranger.c.s
.PHONY : arranger.s

# target to generate assembly for a file
arranger.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/arranger.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/arranger.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/arranger.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/arranger.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/arranger.c.s
.PHONY : arranger.c.s

cmd.o: cmd.c.o
.PHONY : cmd.o

# target to build an object file
cmd.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/cmd.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/cmd.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/cmd.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/cmd.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/cmd.c.o
.PHONY : cmd.c.o

cmd.i: cmd.c.i
.PHONY : cmd.i

# target to preprocess a source file
cmd.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/cmd.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/cmd.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/cmd.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/cmd.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/cmd.c.i
.PHONY : cmd.c.i

cmd.s: cmd.c.s
.PHONY : cmd.s

# target to generate assembly for a file
cmd.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/cmd.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/cmd.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/cmd.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/cmd.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/cmd.c.s
.PHONY : cmd.c.s

common/common.o: common/common.c.o
.PHONY : common/common.o

# target to build an object file
common/common.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/common.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/common.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/common.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/common.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/common.c.o
.PHONY : common/common.c.o

common/common.i: common/common.c.i
.PHONY : common/common.i

# target to preprocess a source file
common/common.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/common.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/common.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/common.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/common.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/common.c.i
.PHONY : common/common.c.i

common/common.s: common/common.c.s
.PHONY : common/common.s

# target to generate assembly for a file
common/common.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/common.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/common.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/common.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/common.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/common.c.s
.PHONY : common/common.c.s

common/fbit.o: common/fbit.c.o
.PHONY : common/fbit.o

# target to build an object file
common/fbit.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fbit.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fbit.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fbit.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fbit.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fbit.c.o
.PHONY : common/fbit.c.o

common/fbit.i: common/fbit.c.i
.PHONY : common/fbit.i

# target to preprocess a source file
common/fbit.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fbit.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fbit.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fbit.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fbit.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fbit.c.i
.PHONY : common/fbit.c.i

common/fbit.s: common/fbit.c.s
.PHONY : common/fbit.s

# target to generate assembly for a file
common/fbit.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fbit.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fbit.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fbit.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fbit.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fbit.c.s
.PHONY : common/fbit.c.s

common/flist.o: common/flist.c.o
.PHONY : common/flist.o

# target to build an object file
common/flist.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/flist.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/flist.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/flist.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/flist.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/flist.c.o
.PHONY : common/flist.c.o

common/flist.i: common/flist.c.i
.PHONY : common/flist.i

# target to preprocess a source file
common/flist.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/flist.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/flist.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/flist.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/flist.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/flist.c.i
.PHONY : common/flist.c.i

common/flist.s: common/flist.c.s
.PHONY : common/flist.s

# target to generate assembly for a file
common/flist.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/flist.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/flist.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/flist.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/flist.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/flist.c.s
.PHONY : common/flist.c.s

common/flog.o: common/flog.c.o
.PHONY : common/flog.o

# target to build an object file
common/flog.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/flog.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/flog.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/flog.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/flog.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/flog.c.o
.PHONY : common/flog.c.o

common/flog.i: common/flog.c.i
.PHONY : common/flog.i

# target to preprocess a source file
common/flog.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/flog.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/flog.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/flog.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/flog.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/flog.c.i
.PHONY : common/flog.c.i

common/flog.s: common/flog.c.s
.PHONY : common/flog.s

# target to generate assembly for a file
common/flog.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/flog.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/flog.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/flog.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/flog.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/flog.c.s
.PHONY : common/flog.c.s

common/fmap.o: common/fmap.c.o
.PHONY : common/fmap.o

# target to build an object file
common/fmap.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fmap.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fmap.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fmap.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fmap.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fmap.c.o
.PHONY : common/fmap.c.o

common/fmap.i: common/fmap.c.i
.PHONY : common/fmap.i

# target to preprocess a source file
common/fmap.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fmap.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fmap.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fmap.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fmap.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fmap.c.i
.PHONY : common/fmap.c.i

common/fmap.s: common/fmap.c.s
.PHONY : common/fmap.s

# target to generate assembly for a file
common/fmap.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fmap.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fmap.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fmap.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fmap.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fmap.c.s
.PHONY : common/fmap.c.s

common/fmem.o: common/fmem.c.o
.PHONY : common/fmem.o

# target to build an object file
common/fmem.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fmem.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fmem.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fmem.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fmem.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fmem.c.o
.PHONY : common/fmem.c.o

common/fmem.i: common/fmem.c.i
.PHONY : common/fmem.i

# target to preprocess a source file
common/fmem.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fmem.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fmem.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fmem.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fmem.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fmem.c.i
.PHONY : common/fmem.c.i

common/fmem.s: common/fmem.c.s
.PHONY : common/fmem.s

# target to generate assembly for a file
common/fmem.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fmem.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fmem.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fmem.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fmem.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fmem.c.s
.PHONY : common/fmem.c.s

common/fqueue.o: common/fqueue.c.o
.PHONY : common/fqueue.o

# target to build an object file
common/fqueue.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fqueue.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fqueue.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fqueue.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fqueue.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fqueue.c.o
.PHONY : common/fqueue.c.o

common/fqueue.i: common/fqueue.c.i
.PHONY : common/fqueue.i

# target to preprocess a source file
common/fqueue.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fqueue.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fqueue.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fqueue.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fqueue.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fqueue.c.i
.PHONY : common/fqueue.c.i

common/fqueue.s: common/fqueue.c.s
.PHONY : common/fqueue.s

# target to generate assembly for a file
common/fqueue.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fqueue.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fqueue.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fqueue.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fqueue.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fqueue.c.s
.PHONY : common/fqueue.c.s

common/fstr.o: common/fstr.c.o
.PHONY : common/fstr.o

# target to build an object file
common/fstr.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fstr.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fstr.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fstr.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fstr.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fstr.c.o
.PHONY : common/fstr.c.o

common/fstr.i: common/fstr.c.i
.PHONY : common/fstr.i

# target to preprocess a source file
common/fstr.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fstr.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fstr.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fstr.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fstr.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fstr.c.i
.PHONY : common/fstr.c.i

common/fstr.s: common/fstr.c.s
.PHONY : common/fstr.s

# target to generate assembly for a file
common/fstr.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/common/fstr.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/common/fstr.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/common/fstr.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/common/fstr.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/common/fstr.c.s
.PHONY : common/fstr.c.s

event.o: event.c.o
.PHONY : event.o

# target to build an object file
event.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/event.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/event.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/event.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/event.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/event.c.o
.PHONY : event.c.o

event.i: event.c.i
.PHONY : event.i

# target to preprocess a source file
event.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/event.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/event.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/event.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/event.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/event.c.i
.PHONY : event.c.i

event.s: event.c.s
.PHONY : event.s

# target to generate assembly for a file
event.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/event.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/event.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/event.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/event.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/event.c.s
.PHONY : event.c.s

net.o: net.c.o
.PHONY : net.o

# target to build an object file
net.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/net.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/net.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/net.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/net.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/net.c.o
.PHONY : net.c.o

net.i: net.c.i
.PHONY : net.i

# target to preprocess a source file
net.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/net.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/net.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/net.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/net.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/net.c.i
.PHONY : net.c.i

net.s: net.c.s
.PHONY : net.s

# target to generate assembly for a file
net.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/net.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/net.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/net.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/net.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/net.c.s
.PHONY : net.c.s

proto/meta.pb.o: proto/meta.pb.cc.o
.PHONY : proto/meta.pb.o

# target to build an object file
proto/meta.pb.cc.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/proto/meta.pb.cc.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/proto/meta.pb.cc.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/proto/meta.pb.cc.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/proto/meta.pb.cc.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/proto/meta.pb.cc.o
.PHONY : proto/meta.pb.cc.o

proto/meta.pb.i: proto/meta.pb.cc.i
.PHONY : proto/meta.pb.i

# target to preprocess a source file
proto/meta.pb.cc.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/proto/meta.pb.cc.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/proto/meta.pb.cc.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/proto/meta.pb.cc.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/proto/meta.pb.cc.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/proto/meta.pb.cc.i
.PHONY : proto/meta.pb.cc.i

proto/meta.pb.s: proto/meta.pb.cc.s
.PHONY : proto/meta.pb.s

# target to generate assembly for a file
proto/meta.pb.cc.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/proto/meta.pb.cc.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/proto/meta.pb.cc.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/proto/meta.pb.cc.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/proto/meta.pb.cc.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/proto/meta.pb.cc.s
.PHONY : proto/meta.pb.cc.s

proto/modelService.pb.o: proto/modelService.pb.cc.o
.PHONY : proto/modelService.pb.o

# target to build an object file
proto/modelService.pb.cc.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/proto/modelService.pb.cc.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/proto/modelService.pb.cc.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/proto/modelService.pb.cc.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/proto/modelService.pb.cc.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/proto/modelService.pb.cc.o
.PHONY : proto/modelService.pb.cc.o

proto/modelService.pb.i: proto/modelService.pb.cc.i
.PHONY : proto/modelService.pb.i

# target to preprocess a source file
proto/modelService.pb.cc.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/proto/modelService.pb.cc.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/proto/modelService.pb.cc.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/proto/modelService.pb.cc.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/proto/modelService.pb.cc.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/proto/modelService.pb.cc.i
.PHONY : proto/modelService.pb.cc.i

proto/modelService.pb.s: proto/modelService.pb.cc.s
.PHONY : proto/modelService.pb.s

# target to generate assembly for a file
proto/modelService.pb.cc.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/proto/modelService.pb.cc.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/proto/modelService.pb.cc.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/proto/modelService.pb.cc.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/proto/modelService.pb.cc.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/proto/modelService.pb.cc.s
.PHONY : proto/modelService.pb.cc.s

threadpool.o: threadpool.c.o
.PHONY : threadpool.o

# target to build an object file
threadpool.c.o:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/threadpool.c.o
.PHONY : threadpool.c.o

threadpool.i: threadpool.c.i
.PHONY : threadpool.i

# target to preprocess a source file
threadpool.c.i:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/threadpool.c.i
.PHONY : threadpool.c.i

threadpool.s: threadpool.c.s
.PHONY : threadpool.s

# target to generate assembly for a file
threadpool.c.s:
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/threadpool.c.s
.PHONY : threadpool.c.s

webc.o: webc.c.o
.PHONY : webc.o

# target to build an object file
webc.c.o:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/webc.c.o
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/webc.c.o
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/webc.c.o
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/webc.c.o
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/webc.c.o
.PHONY : webc.c.o

webc.i: webc.c.i
.PHONY : webc.i

# target to preprocess a source file
webc.c.i:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/webc.c.i
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/webc.c.i
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/webc.c.i
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/webc.c.i
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/webc.c.i
.PHONY : webc.c.i

webc.s: webc.c.s
.PHONY : webc.s

# target to generate assembly for a file
webc.c.s:
	$(MAKE) -f CMakeFiles/consumer.dir/build.make CMakeFiles/consumer.dir/webc.c.s
	$(MAKE) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/webc.c.s
	$(MAKE) -f CMakeFiles/threadpool.dir/build.make CMakeFiles/threadpool.dir/webc.c.s
	$(MAKE) -f CMakeFiles/webc.dir/build.make CMakeFiles/webc.dir/webc.c.s
	$(MAKE) -f CMakeFiles/worker.dir/build.make CMakeFiles/worker.dir/webc.c.s
.PHONY : webc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... threadpool"
	@echo "... worker"
	@echo "... webc"
	@echo "... consumer"
	@echo "... provider"
	@echo "... RpcConsumer.o"
	@echo "... RpcConsumer.i"
	@echo "... RpcConsumer.s"
	@echo "... RpcServer.o"
	@echo "... RpcServer.i"
	@echo "... RpcServer.s"
	@echo "... Woker.o"
	@echo "... Woker.i"
	@echo "... Woker.s"
	@echo "... arranger.o"
	@echo "... arranger.i"
	@echo "... arranger.s"
	@echo "... cmd.o"
	@echo "... cmd.i"
	@echo "... cmd.s"
	@echo "... common/common.o"
	@echo "... common/common.i"
	@echo "... common/common.s"
	@echo "... common/fbit.o"
	@echo "... common/fbit.i"
	@echo "... common/fbit.s"
	@echo "... common/flist.o"
	@echo "... common/flist.i"
	@echo "... common/flist.s"
	@echo "... common/flog.o"
	@echo "... common/flog.i"
	@echo "... common/flog.s"
	@echo "... common/fmap.o"
	@echo "... common/fmap.i"
	@echo "... common/fmap.s"
	@echo "... common/fmem.o"
	@echo "... common/fmem.i"
	@echo "... common/fmem.s"
	@echo "... common/fqueue.o"
	@echo "... common/fqueue.i"
	@echo "... common/fqueue.s"
	@echo "... common/fstr.o"
	@echo "... common/fstr.i"
	@echo "... common/fstr.s"
	@echo "... event.o"
	@echo "... event.i"
	@echo "... event.s"
	@echo "... net.o"
	@echo "... net.i"
	@echo "... net.s"
	@echo "... proto/meta.pb.o"
	@echo "... proto/meta.pb.i"
	@echo "... proto/meta.pb.s"
	@echo "... proto/modelService.pb.o"
	@echo "... proto/modelService.pb.i"
	@echo "... proto/modelService.pb.s"
	@echo "... threadpool.o"
	@echo "... threadpool.i"
	@echo "... threadpool.s"
	@echo "... webc.o"
	@echo "... webc.i"
	@echo "... webc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

