// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ArrangerService.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/ArrangerService.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace fankux {

namespace {

const ::google::protobuf::ServiceDescriptor* ArrangerService_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2fArrangerService_2eproto() {
  protobuf_AddDesc_proto_2fArrangerService_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/ArrangerService.proto");
  GOOGLE_CHECK(file != NULL);
  ArrangerService_descriptor_ = file->service(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2fArrangerService_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_proto_2fArrangerService_2eproto() {
}

void protobuf_AddDesc_proto_2fArrangerService_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::fankux::protobuf_AddDesc_proto_2fheartbeat_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033proto/ArrangerService.proto\022\006fankux\032\025p"
    "roto/heartbeat.proto2N\n\017ArrangerService\022"
    ";\n\004echo\022\030.fankux.HeartbeatRequest\032\031.fank"
    "ux.HeartbeatResponseB\003\200\001\001", 145);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/ArrangerService.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2fArrangerService_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2fArrangerService_2eproto {
  StaticDescriptorInitializer_proto_2fArrangerService_2eproto() {
    protobuf_AddDesc_proto_2fArrangerService_2eproto();
  }
} static_descriptor_initializer_proto_2fArrangerService_2eproto_;

// ===================================================================

ArrangerService::~ArrangerService() {}

const ::google::protobuf::ServiceDescriptor* ArrangerService::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ArrangerService_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* ArrangerService::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return ArrangerService_descriptor_;
}

void ArrangerService::echo(::google::protobuf::RpcController* controller,
                         const ::fankux::HeartbeatRequest*,
                         ::fankux::HeartbeatResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method echo() not implemented.");
  done->Run();
}

void ArrangerService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), ArrangerService_descriptor_);
  switch(method->index()) {
    case 0:
      echo(controller,
             ::google::protobuf::down_cast<const ::fankux::HeartbeatRequest*>(request),
             ::google::protobuf::down_cast< ::fankux::HeartbeatResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& ArrangerService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::fankux::HeartbeatRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& ArrangerService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::fankux::HeartbeatResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

ArrangerService_Stub::ArrangerService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
ArrangerService_Stub::ArrangerService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
ArrangerService_Stub::~ArrangerService_Stub() {
  if (owns_channel_) delete channel_;
}

void ArrangerService_Stub::echo(::google::protobuf::RpcController* controller,
                              const ::fankux::HeartbeatRequest* request,
                              ::fankux::HeartbeatResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace fankux

// @@protoc_insertion_point(global_scope)
