// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/meta.proto

#ifndef PROTOBUF_proto_2fmeta_2eproto__INCLUDED
#define PROTOBUF_proto_2fmeta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace fdis {
class RequestMeta;
class RequestMetaDefaultTypeInternal;
extern RequestMetaDefaultTypeInternal _RequestMeta_default_instance_;
class ResponseStatus;
class ResponseStatusDefaultTypeInternal;
extern ResponseStatusDefaultTypeInternal _ResponseStatus_default_instance_;
}  // namespace fdis

namespace fdis {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fmeta_2eproto();
void protobuf_InitDefaults_proto_2fmeta_2eproto();

// ===================================================================

class RequestMeta : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fdis.RequestMeta) */ {
 public:
  RequestMeta();
  virtual ~RequestMeta();

  RequestMeta(const RequestMeta& from);

  inline RequestMeta& operator=(const RequestMeta& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestMeta& default_instance();

  static inline const RequestMeta* internal_default_instance() {
    return reinterpret_cast<const RequestMeta*>(
               &_RequestMeta_default_instance_);
  }

  void Swap(RequestMeta* other);

  // implements Message ----------------------------------------------

  inline RequestMeta* New() const PROTOBUF_FINAL { return New(NULL); }

  RequestMeta* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RequestMeta& from);
  void MergeFrom(const RequestMeta& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RequestMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 service_id = 1;
  bool has_service_id() const;
  void clear_service_id();
  static const int kServiceIdFieldNumber = 1;
  ::google::protobuf::int32 service_id() const;
  void set_service_id(::google::protobuf::int32 value);

  // required int32 method_id = 2;
  bool has_method_id() const;
  void clear_method_id();
  static const int kMethodIdFieldNumber = 2;
  ::google::protobuf::int32 method_id() const;
  void set_method_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fdis.RequestMeta)
 private:
  void set_has_service_id();
  void clear_has_service_id();
  void set_has_method_id();
  void clear_has_method_id();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 service_id_;
  ::google::protobuf::int32 method_id_;
  friend void  protobuf_InitDefaults_proto_2fmeta_2eproto_impl();
  friend void  protobuf_AddDesc_proto_2fmeta_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_proto_2fmeta_2eproto();
  friend void protobuf_ShutdownFile_proto_2fmeta_2eproto();

};
// -------------------------------------------------------------------

class ResponseStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fdis.ResponseStatus) */ {
 public:
  ResponseStatus();
  virtual ~ResponseStatus();

  ResponseStatus(const ResponseStatus& from);

  inline ResponseStatus& operator=(const ResponseStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseStatus& default_instance();

  static inline const ResponseStatus* internal_default_instance() {
    return reinterpret_cast<const ResponseStatus*>(
               &_ResponseStatus_default_instance_);
  }

  void Swap(ResponseStatus* other);

  // implements Message ----------------------------------------------

  inline ResponseStatus* New() const PROTOBUF_FINAL { return New(NULL); }

  ResponseStatus* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResponseStatus& from);
  void MergeFrom(const ResponseStatus& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResponseStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 status = 1;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // optional string message = 2;
  bool has_message() const;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:fdis.ResponseStatus)
 private:
  void set_has_status();
  void clear_has_status();
  void set_has_message();
  void clear_has_message();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_InitDefaults_proto_2fmeta_2eproto_impl();
  friend void  protobuf_AddDesc_proto_2fmeta_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_proto_2fmeta_2eproto();
  friend void protobuf_ShutdownFile_proto_2fmeta_2eproto();

};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestMeta

// required int32 service_id = 1;
inline bool RequestMeta::has_service_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestMeta::set_has_service_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestMeta::clear_has_service_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestMeta::clear_service_id() {
  service_id_ = 0;
  clear_has_service_id();
}
inline ::google::protobuf::int32 RequestMeta::service_id() const {
  // @@protoc_insertion_point(field_get:fdis.RequestMeta.service_id)
  return service_id_;
}
inline void RequestMeta::set_service_id(::google::protobuf::int32 value) {
  set_has_service_id();
  service_id_ = value;
  // @@protoc_insertion_point(field_set:fdis.RequestMeta.service_id)
}

// required int32 method_id = 2;
inline bool RequestMeta::has_method_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestMeta::set_has_method_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestMeta::clear_has_method_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestMeta::clear_method_id() {
  method_id_ = 0;
  clear_has_method_id();
}
inline ::google::protobuf::int32 RequestMeta::method_id() const {
  // @@protoc_insertion_point(field_get:fdis.RequestMeta.method_id)
  return method_id_;
}
inline void RequestMeta::set_method_id(::google::protobuf::int32 value) {
  set_has_method_id();
  method_id_ = value;
  // @@protoc_insertion_point(field_set:fdis.RequestMeta.method_id)
}

// -------------------------------------------------------------------

// ResponseStatus

// required int32 status = 1;
inline bool ResponseStatus::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseStatus::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseStatus::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseStatus::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 ResponseStatus::status() const {
  // @@protoc_insertion_point(field_get:fdis.ResponseStatus.status)
  return status_;
}
inline void ResponseStatus::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:fdis.ResponseStatus.status)
}

// optional string message = 2;
inline bool ResponseStatus::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseStatus::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseStatus::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseStatus::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message();
}
inline const ::std::string& ResponseStatus::message() const {
  // @@protoc_insertion_point(field_get:fdis.ResponseStatus.message)
  return message_.GetNoArena();
}
inline void ResponseStatus::set_message(const ::std::string& value) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fdis.ResponseStatus.message)
}
inline void ResponseStatus::set_message(const char* value) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fdis.ResponseStatus.message)
}
inline void ResponseStatus::set_message(const char* value, size_t size) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fdis.ResponseStatus.message)
}
inline ::std::string* ResponseStatus::mutable_message() {
  set_has_message();
  // @@protoc_insertion_point(field_mutable:fdis.ResponseStatus.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponseStatus::release_message() {
  // @@protoc_insertion_point(field_release:fdis.ResponseStatus.message)
  clear_has_message();
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponseStatus::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    set_has_message();
  } else {
    clear_has_message();
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:fdis.ResponseStatus.message)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace fdis

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fmeta_2eproto__INCLUDED
