// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/meta.proto

#ifndef PROTOBUF_proto_2fmeta_2eproto__INCLUDED
#define PROTOBUF_proto_2fmeta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace fankux {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fmeta_2eproto();
void protobuf_AssignDesc_proto_2fmeta_2eproto();
void protobuf_ShutdownFile_proto_2fmeta_2eproto();

class RequestMeta;
class ResponseStatus;

// ===================================================================

class RequestMeta : public ::google::protobuf::Message {
 public:
  RequestMeta();
  virtual ~RequestMeta();

  RequestMeta(const RequestMeta& from);

  inline RequestMeta& operator=(const RequestMeta& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestMeta& default_instance();

  void Swap(RequestMeta* other);

  // implements Message ----------------------------------------------

  RequestMeta* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestMeta& from);
  void MergeFrom(const RequestMeta& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 service_id = 1;
  inline bool has_service_id() const;
  inline void clear_service_id();
  static const int kServiceIdFieldNumber = 1;
  inline ::google::protobuf::int32 service_id() const;
  inline void set_service_id(::google::protobuf::int32 value);

  // required int32 method_id = 2;
  inline bool has_method_id() const;
  inline void clear_method_id();
  static const int kMethodIdFieldNumber = 2;
  inline ::google::protobuf::int32 method_id() const;
  inline void set_method_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fankux.RequestMeta)
 private:
  inline void set_has_service_id();
  inline void clear_has_service_id();
  inline void set_has_method_id();
  inline void clear_has_method_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 service_id_;
  ::google::protobuf::int32 method_id_;
  friend void  protobuf_AddDesc_proto_2fmeta_2eproto();
  friend void protobuf_AssignDesc_proto_2fmeta_2eproto();
  friend void protobuf_ShutdownFile_proto_2fmeta_2eproto();

  void InitAsDefaultInstance();
  static RequestMeta* default_instance_;
};
// -------------------------------------------------------------------

class ResponseStatus : public ::google::protobuf::Message {
 public:
  ResponseStatus();
  virtual ~ResponseStatus();

  ResponseStatus(const ResponseStatus& from);

  inline ResponseStatus& operator=(const ResponseStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseStatus& default_instance();

  void Swap(ResponseStatus* other);

  // implements Message ----------------------------------------------

  ResponseStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseStatus& from);
  void MergeFrom(const ResponseStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // optional string msg = 2;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 2;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const char* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:fankux.ResponseStatus)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_msg();
  inline void clear_has_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* msg_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_proto_2fmeta_2eproto();
  friend void protobuf_AssignDesc_proto_2fmeta_2eproto();
  friend void protobuf_ShutdownFile_proto_2fmeta_2eproto();

  void InitAsDefaultInstance();
  static ResponseStatus* default_instance_;
};
// ===================================================================


// ===================================================================

// RequestMeta

// required int32 service_id = 1;
inline bool RequestMeta::has_service_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestMeta::set_has_service_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestMeta::clear_has_service_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestMeta::clear_service_id() {
  service_id_ = 0;
  clear_has_service_id();
}
inline ::google::protobuf::int32 RequestMeta::service_id() const {
  // @@protoc_insertion_point(field_get:fankux.RequestMeta.service_id)
  return service_id_;
}
inline void RequestMeta::set_service_id(::google::protobuf::int32 value) {
  set_has_service_id();
  service_id_ = value;
  // @@protoc_insertion_point(field_set:fankux.RequestMeta.service_id)
}

// required int32 method_id = 2;
inline bool RequestMeta::has_method_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestMeta::set_has_method_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestMeta::clear_has_method_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestMeta::clear_method_id() {
  method_id_ = 0;
  clear_has_method_id();
}
inline ::google::protobuf::int32 RequestMeta::method_id() const {
  // @@protoc_insertion_point(field_get:fankux.RequestMeta.method_id)
  return method_id_;
}
inline void RequestMeta::set_method_id(::google::protobuf::int32 value) {
  set_has_method_id();
  method_id_ = value;
  // @@protoc_insertion_point(field_set:fankux.RequestMeta.method_id)
}

// -------------------------------------------------------------------

// ResponseStatus

// required int32 status = 1;
inline bool ResponseStatus::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseStatus::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseStatus::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseStatus::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 ResponseStatus::status() const {
  // @@protoc_insertion_point(field_get:fankux.ResponseStatus.status)
  return status_;
}
inline void ResponseStatus::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:fankux.ResponseStatus.status)
}

// optional string msg = 2;
inline bool ResponseStatus::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseStatus::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseStatus::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseStatus::clear_msg() {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& ResponseStatus::msg() const {
  // @@protoc_insertion_point(field_get:fankux.ResponseStatus.msg)
  return *msg_;
}
inline void ResponseStatus::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set:fankux.ResponseStatus.msg)
}
inline void ResponseStatus::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:fankux.ResponseStatus.msg)
}
inline void ResponseStatus::set_msg(const char* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fankux.ResponseStatus.msg)
}
inline ::std::string* ResponseStatus::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:fankux.ResponseStatus.msg)
  return msg_;
}
inline ::std::string* ResponseStatus::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ResponseStatus::set_allocated_msg(::std::string* msg) {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_;
  }
  if (msg) {
    set_has_msg();
    msg_ = msg;
  } else {
    clear_has_msg();
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:fankux.ResponseStatus.msg)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace fankux

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fmeta_2eproto__INCLUDED
