// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/WorkerService.proto

#ifndef PROTOBUF_proto_2fWorkerService_2eproto__INCLUDED
#define PROTOBUF_proto_2fWorkerService_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/heartbeat.pb.h"
// @@protoc_insertion_point(includes)

namespace fdis {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fWorkerService_2eproto();
void protobuf_AssignDesc_proto_2fWorkerService_2eproto();
void protobuf_ShutdownFile_proto_2fWorkerService_2eproto();

class WriteBuffer;
class WriteResponse;

// ===================================================================

class WriteBuffer : public ::google::protobuf::Message {
 public:
  WriteBuffer();
  virtual ~WriteBuffer();

  WriteBuffer(const WriteBuffer& from);

  inline WriteBuffer& operator=(const WriteBuffer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteBuffer& default_instance();

  void Swap(WriteBuffer* other);

  // implements Message ----------------------------------------------

  WriteBuffer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteBuffer& from);
  void MergeFrom(const WriteBuffer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 len = 1;
  inline bool has_len() const;
  inline void clear_len();
  static const int kLenFieldNumber = 1;
  inline ::google::protobuf::uint64 len() const;
  inline void set_len(::google::protobuf::uint64 value);

  // required bytes buffer = 2;
  inline bool has_buffer() const;
  inline void clear_buffer();
  static const int kBufferFieldNumber = 2;
  inline const ::std::string& buffer() const;
  inline void set_buffer(const ::std::string& value);
  inline void set_buffer(const char* value);
  inline void set_buffer(const void* value, size_t size);
  inline ::std::string* mutable_buffer();
  inline ::std::string* release_buffer();
  inline void set_allocated_buffer(::std::string* buffer);

  // @@protoc_insertion_point(class_scope:fdis.WriteBuffer)
 private:
  inline void set_has_len();
  inline void clear_has_len();
  inline void set_has_buffer();
  inline void clear_has_buffer();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 len_;
  ::std::string* buffer_;
  friend void  protobuf_AddDesc_proto_2fWorkerService_2eproto();
  friend void protobuf_AssignDesc_proto_2fWorkerService_2eproto();
  friend void protobuf_ShutdownFile_proto_2fWorkerService_2eproto();

  void InitAsDefaultInstance();
  static WriteBuffer* default_instance_;
};
// -------------------------------------------------------------------

class WriteResponse : public ::google::protobuf::Message {
 public:
  WriteResponse();
  virtual ~WriteResponse();

  WriteResponse(const WriteResponse& from);

  inline WriteResponse& operator=(const WriteResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteResponse& default_instance();

  void Swap(WriteResponse* other);

  // implements Message ----------------------------------------------

  WriteResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteResponse& from);
  void MergeFrom(const WriteResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 len = 1;
  inline bool has_len() const;
  inline void clear_len();
  static const int kLenFieldNumber = 1;
  inline ::google::protobuf::uint64 len() const;
  inline void set_len(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:fdis.WriteResponse)
 private:
  inline void set_has_len();
  inline void clear_has_len();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 len_;
  friend void  protobuf_AddDesc_proto_2fWorkerService_2eproto();
  friend void protobuf_AssignDesc_proto_2fWorkerService_2eproto();
  friend void protobuf_ShutdownFile_proto_2fWorkerService_2eproto();

  void InitAsDefaultInstance();
  static WriteResponse* default_instance_;
};
// ===================================================================

class WorkerService_Stub;

class WorkerService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline WorkerService() {};
 public:
  virtual ~WorkerService();

  typedef WorkerService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void echo(::google::protobuf::RpcController* controller,
                       const ::fdis::HeartbeatRequest* request,
                       ::fdis::HeartbeatResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkerService);
};

class WorkerService_Stub : public WorkerService {
 public:
  WorkerService_Stub(::google::protobuf::RpcChannel* channel);
  WorkerService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~WorkerService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements WorkerService ------------------------------------------

  void echo(::google::protobuf::RpcController* controller,
                       const ::fdis::HeartbeatRequest* request,
                       ::fdis::HeartbeatResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkerService_Stub);
};


// ===================================================================


// ===================================================================

// WriteBuffer

// required uint64 len = 1;
inline bool WriteBuffer::has_len() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WriteBuffer::set_has_len() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WriteBuffer::clear_has_len() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WriteBuffer::clear_len() {
  len_ = GOOGLE_ULONGLONG(0);
  clear_has_len();
}
inline ::google::protobuf::uint64 WriteBuffer::len() const {
  // @@protoc_insertion_point(field_get:fdis.WriteBuffer.len)
  return len_;
}
inline void WriteBuffer::set_len(::google::protobuf::uint64 value) {
  set_has_len();
  len_ = value;
  // @@protoc_insertion_point(field_set:fdis.WriteBuffer.len)
}

// required bytes buffer = 2;
inline bool WriteBuffer::has_buffer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WriteBuffer::set_has_buffer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WriteBuffer::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WriteBuffer::clear_buffer() {
  if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_->clear();
  }
  clear_has_buffer();
}
inline const ::std::string& WriteBuffer::buffer() const {
  // @@protoc_insertion_point(field_get:fdis.WriteBuffer.buffer)
  return *buffer_;
}
inline void WriteBuffer::set_buffer(const ::std::string& value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
  // @@protoc_insertion_point(field_set:fdis.WriteBuffer.buffer)
}
inline void WriteBuffer::set_buffer(const char* value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
  // @@protoc_insertion_point(field_set_char:fdis.WriteBuffer.buffer)
}
inline void WriteBuffer::set_buffer(const void* value, size_t size) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fdis.WriteBuffer.buffer)
}
inline ::std::string* WriteBuffer::mutable_buffer() {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:fdis.WriteBuffer.buffer)
  return buffer_;
}
inline ::std::string* WriteBuffer::release_buffer() {
  clear_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = buffer_;
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void WriteBuffer::set_allocated_buffer(::std::string* buffer) {
  if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete buffer_;
  }
  if (buffer) {
    set_has_buffer();
    buffer_ = buffer;
  } else {
    clear_has_buffer();
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:fdis.WriteBuffer.buffer)
}

// -------------------------------------------------------------------

// WriteResponse

// required uint64 len = 1;
inline bool WriteResponse::has_len() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WriteResponse::set_has_len() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WriteResponse::clear_has_len() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WriteResponse::clear_len() {
  len_ = GOOGLE_ULONGLONG(0);
  clear_has_len();
}
inline ::google::protobuf::uint64 WriteResponse::len() const {
  // @@protoc_insertion_point(field_get:fdis.WriteResponse.len)
  return len_;
}
inline void WriteResponse::set_len(::google::protobuf::uint64 value) {
  set_has_len();
  len_ = value;
  // @@protoc_insertion_point(field_set:fdis.WriteResponse.len)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace fdis

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fWorkerService_2eproto__INCLUDED
