// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/WorkerService.proto

#ifndef PROTOBUF_proto_2fWorkerService_2eproto__INCLUDED
#define PROTOBUF_proto_2fWorkerService_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/heartbeat.pb.h"
// @@protoc_insertion_point(includes)
namespace fdis {
class HeartbeatRequest;
class HeartbeatRequestDefaultTypeInternal;
extern HeartbeatRequestDefaultTypeInternal _HeartbeatRequest_default_instance_;
class HeartbeatResponse;
class HeartbeatResponseDefaultTypeInternal;
extern HeartbeatResponseDefaultTypeInternal _HeartbeatResponse_default_instance_;
class WriteBuffer;
class WriteBufferDefaultTypeInternal;
extern WriteBufferDefaultTypeInternal _WriteBuffer_default_instance_;
class WriteResponse;
class WriteResponseDefaultTypeInternal;
extern WriteResponseDefaultTypeInternal _WriteResponse_default_instance_;
}  // namespace fdis

namespace fdis {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fWorkerService_2eproto();
void protobuf_InitDefaults_proto_2fWorkerService_2eproto();

// ===================================================================

class WriteBuffer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fdis.WriteBuffer) */ {
 public:
  WriteBuffer();
  virtual ~WriteBuffer();

  WriteBuffer(const WriteBuffer& from);

  inline WriteBuffer& operator=(const WriteBuffer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteBuffer& default_instance();

  static inline const WriteBuffer* internal_default_instance() {
    return reinterpret_cast<const WriteBuffer*>(
               &_WriteBuffer_default_instance_);
  }

  void Swap(WriteBuffer* other);

  // implements Message ----------------------------------------------

  inline WriteBuffer* New() const PROTOBUF_FINAL { return New(NULL); }

  WriteBuffer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WriteBuffer& from);
  void MergeFrom(const WriteBuffer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WriteBuffer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 len = 1;
  bool has_len() const;
  void clear_len();
  static const int kLenFieldNumber = 1;
  ::google::protobuf::uint64 len() const;
  void set_len(::google::protobuf::uint64 value);

  // required bytes buffer = 2;
  bool has_buffer() const;
  void clear_buffer();
  static const int kBufferFieldNumber = 2;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // @@protoc_insertion_point(class_scope:fdis.WriteBuffer)
 private:
  void set_has_len();
  void clear_has_len();
  void set_has_buffer();
  void clear_has_buffer();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  ::google::protobuf::uint64 len_;
  friend void  protobuf_InitDefaults_proto_2fWorkerService_2eproto_impl();
  friend void  protobuf_AddDesc_proto_2fWorkerService_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_proto_2fWorkerService_2eproto();
  friend void protobuf_ShutdownFile_proto_2fWorkerService_2eproto();

};
// -------------------------------------------------------------------

class WriteResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fdis.WriteResponse) */ {
 public:
  WriteResponse();
  virtual ~WriteResponse();

  WriteResponse(const WriteResponse& from);

  inline WriteResponse& operator=(const WriteResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteResponse& default_instance();

  static inline const WriteResponse* internal_default_instance() {
    return reinterpret_cast<const WriteResponse*>(
               &_WriteResponse_default_instance_);
  }

  void Swap(WriteResponse* other);

  // implements Message ----------------------------------------------

  inline WriteResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  WriteResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WriteResponse& from);
  void MergeFrom(const WriteResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WriteResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 len = 1;
  bool has_len() const;
  void clear_len();
  static const int kLenFieldNumber = 1;
  ::google::protobuf::uint64 len() const;
  void set_len(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:fdis.WriteResponse)
 private:
  void set_has_len();
  void clear_has_len();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 len_;
  friend void  protobuf_InitDefaults_proto_2fWorkerService_2eproto_impl();
  friend void  protobuf_AddDesc_proto_2fWorkerService_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_proto_2fWorkerService_2eproto();
  friend void protobuf_ShutdownFile_proto_2fWorkerService_2eproto();

};
// ===================================================================

class WorkerService_Stub;

class WorkerService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline WorkerService() {};
 public:
  virtual ~WorkerService();

  typedef WorkerService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void echo(::google::protobuf::RpcController* controller,
                       const ::fdis::HeartbeatRequest* request,
                       ::fdis::HeartbeatResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkerService);
};

class WorkerService_Stub : public WorkerService {
 public:
  WorkerService_Stub(::google::protobuf::RpcChannel* channel);
  WorkerService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~WorkerService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements WorkerService ------------------------------------------

  void echo(::google::protobuf::RpcController* controller,
                       const ::fdis::HeartbeatRequest* request,
                       ::fdis::HeartbeatResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorkerService_Stub);
};


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// WriteBuffer

// required uint64 len = 1;
inline bool WriteBuffer::has_len() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WriteBuffer::set_has_len() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WriteBuffer::clear_has_len() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WriteBuffer::clear_len() {
  len_ = GOOGLE_ULONGLONG(0);
  clear_has_len();
}
inline ::google::protobuf::uint64 WriteBuffer::len() const {
  // @@protoc_insertion_point(field_get:fdis.WriteBuffer.len)
  return len_;
}
inline void WriteBuffer::set_len(::google::protobuf::uint64 value) {
  set_has_len();
  len_ = value;
  // @@protoc_insertion_point(field_set:fdis.WriteBuffer.len)
}

// required bytes buffer = 2;
inline bool WriteBuffer::has_buffer() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WriteBuffer::set_has_buffer() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WriteBuffer::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WriteBuffer::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_buffer();
}
inline const ::std::string& WriteBuffer::buffer() const {
  // @@protoc_insertion_point(field_get:fdis.WriteBuffer.buffer)
  return buffer_.GetNoArena();
}
inline void WriteBuffer::set_buffer(const ::std::string& value) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fdis.WriteBuffer.buffer)
}
inline void WriteBuffer::set_buffer(const char* value) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fdis.WriteBuffer.buffer)
}
inline void WriteBuffer::set_buffer(const void* value, size_t size) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fdis.WriteBuffer.buffer)
}
inline ::std::string* WriteBuffer::mutable_buffer() {
  set_has_buffer();
  // @@protoc_insertion_point(field_mutable:fdis.WriteBuffer.buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WriteBuffer::release_buffer() {
  // @@protoc_insertion_point(field_release:fdis.WriteBuffer.buffer)
  clear_has_buffer();
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteBuffer::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    set_has_buffer();
  } else {
    clear_has_buffer();
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:fdis.WriteBuffer.buffer)
}

// -------------------------------------------------------------------

// WriteResponse

// required uint64 len = 1;
inline bool WriteResponse::has_len() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WriteResponse::set_has_len() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WriteResponse::clear_has_len() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WriteResponse::clear_len() {
  len_ = GOOGLE_ULONGLONG(0);
  clear_has_len();
}
inline ::google::protobuf::uint64 WriteResponse::len() const {
  // @@protoc_insertion_point(field_get:fdis.WriteResponse.len)
  return len_;
}
inline void WriteResponse::set_len(::google::protobuf::uint64 value) {
  set_has_len();
  len_ = value;
  // @@protoc_insertion_point(field_set:fdis.WriteResponse.len)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace fdis

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fWorkerService_2eproto__INCLUDED
